name: Setup Project Folders

on:
  workflow_dispatch:   # Allows you to run manually
  push:
    branches:
      - main

jobs:
  create-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folders
        run: |
          mkdir -p src/components
          mkdir -p src/pages
          mkdir -p src/styles
          mkdir -p public/assets
          mkdir -p utils

          # Add placeholder files so git tracks them
          touch src/components/.gitkeep
          touch src/pages/.gitkeep
          touch src/styles/.gitkeep
          touch public/assets/.gitkeep
          touch utils/.gitkeep

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Create initial folder structure"
          git push
